### ISSUE TITLE
ssh error root/root

### ISSUE THREAD

**Issue by chenyubupt** [N1nEmAn/Sevnup#2]
![image](https://github.com/N1nEmAn/Sevnup/assets/161668542/14d8759b-b8ca-47e0-a49d-93147df16566)

in mipsel, use username 'root' and password 'root' to login.

how to login ?by ssh?
![image](https://github.com/N1nEmAn/Sevnup/assets/161668542/15f0a41a-ee8b-4ba6-a0c9-10af3e35ec04)

ssh failed when using root/root

**Comment by chenyubupt** [comment]
Can you give a  full demo for me?

**Comment by N1nEmAn** [comment]
No bro, it will create a new window with qemu where you can login as root as a new machine.Don't you get a new window?

Oh I see.From your screenshots it looks like you are using Ubuntu.I recommend you modify some of the scripts yourself if you are using Ubuntu.Because as my README says, this tool is based on Archlinux.

There are many other good tools for Ubuntu, right?I coded this tool because I can't use those tools.

**Comment by N1nEmAn** [comment]
> Can you give a full demo for me?

Hello, now I have updated a demo.
